# Generated by Django 4.2.11 on 2024-03-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
