# Generated by Django 4.2.11 on 2024-03-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='date_added',
        ),
    ]
