# Generated by Django 4.2.11 on 2024-03-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
