# Generated by Django 4.2.11 on 2024-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_wishlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
